# Generated by Django 5.0.2 on 2024-07-28 18:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('plate_number', models.CharField(max_length=255, unique=True)),
                ('company', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_point', models.CharField(max_length=255)),
                ('end_point', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('duration', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('trip_type', models.CharField(choices=[('one_way_trip', 'One Way Trip'), ('round_trip', 'Round Trip')], default='one_way_trip', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_info', models.CharField(max_length=255)),
                ('trip_type', models.CharField(max_length=255)),
                ('departure_datetime', models.DateTimeField()),
                ('return_datetime', models.DateTimeField(blank=True, null=True)),
                ('seat_number', models.IntegerField(default=0)),
                ('number_of_seats', models.IntegerField()),
                ('payment_method', models.CharField(max_length=255)),
                ('payment_details', models.TextField()),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.route')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('company_logo_url', models.URLField()),
                ('company_slogan', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
