# Generated by Django 5.0.2 on 2024-07-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Route',
            new_name='Routes',
        ),
    ]
