# Generated by Django 5.0.2 on 2024-07-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_route_duration_route_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='trip_type',
            field=models.CharField(choices=[('one_way_trip', 'One Way Trip'), ('round_trip', 'Round Trip')], default='one_way_trip', max_length=255),
        ),
    ]
